### ISSUE TITLE
代码疑问

### ISSUE THREAD

**Issue by xiaoerlaigeid** [HadXu/machine-learning#3]
```
def load_image(imageurl):
    im = cv2.resize(cv2.imread(imageurl),(224,224)).astype(np.float32)
    im[:,:,0] -= 103.939
    im[:,:,1] -= 116.779
    im[:,:,2] -= 123.68
    im = im.transpose((2,0,1))
    im = np.expand_dims(im,axis=0)
    return I'm
```
请问这个为什么三个通道要减去这个值？
后面的转置是什么目的？不太懂，希望大神解答下谢谢！

**Comment by HadXu** [comment]
tf端和th端的图片同道不一样，tf是channel_last,而th是channel_first,因此需要图片通道的转换

**Comment by xiaoerlaigeid** [comment]
谢谢解答，那减去的值是什么意思？

**Comment by HadXu** [comment]
```
    if data_format == 'channels_first':
        # 'RGB'->'BGR'
        x = x[:, ::-1, :, :]
        # Zero-center by mean pixel
        x[:, 0, :, :] -= 103.939
        x[:, 1, :, :] -= 116.779
        x[:, 2, :, :] -= 123.68
    else:
        # 'RGB'->'BGR'
        x = x[:, :, :, ::-1]
        # Zero-center by mean `pixel`
        x[:, :, :, 0] -= 103.939
        x[:, :, :, 1] -= 116.779
        x[:, :, :, 2] -= 123.68
    return x
```

**Comment by xiaoerlaigeid** [comment]
我大概明白了一点，但是不应该每一张图片的均值都不一样么？这个数值是怎么计算出来的

**Comment by HadXu** [comment]
不知道了，当时vgg16模型提出来的时候就是这样定义的，有兴趣可以读读VGG16论文

**Comment by xiaoerlaigeid** [comment]
好的，谢谢了！

**Comment by gazrogers** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @alberrrttt, @charles-cai, @zhangxiang958, @sa03, @seasonxin6190, @leonzhang1108, @sunqb, @iRoySwift, @andy521, @fungwan, @hewentaowx, @jhhisnice, @ruandao, @liwf-sama, @saighost, @hanhunhan, @qi90mufeng, @secreter, @amorist, @yuzhaodi, @leeziiAtCn, @jword, @lakshaygaur, @ufoqhmdt, @Latube, @alienwings, @derek521214, @yin-fan, @irvinwang, @holybao, @iwe7, @pre1ude, @homeless2010, @hanmichael, @outhsics, @banianxd, @rabbitz, @yubaoquan, @he426100, @cheney20121, @Techiu, @suckitfa, @thu, @tietang, @cieldon32, @FubukiPoi, @daisyliu618, @371148606, @sq-zhou, @xCss

**Comment by 371148606** [comment]
您好，我是薛文毅，已收到您的邮件，一会查收，谢谢！！
